### ISSUE TITLE
[EPIC] Refactor

### ISSUE THREAD

**Issue by vexandmore** [space-concordia-robotics/robotics-orin-gui#1]
### Short Description
There are various issues with the GUI's code as it stands, mainly organizational.

### Acceptance criteria

- [ ] Request permission to use cameras in localhost:4200/server. Currently, it attempts to open the cameras without asking for permission, so unless the user manually grants this in their browser settings it won't work. This is in enumerateMediaDevices() function of video-server.component.ts, and see [here](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API) for docs on asking for permission. Also show an error when the user denies permission.
- [ ] The way getServerURL() works (in connection_info.ts) is poor. It hardcodes the remote IP of the server (192.168.0.10, this is the Jetson's IP on our router) when it should figure it out dynamically (likely using window.location.host)
- [ ] Understand why there are two web servers - on port 4200 and 5000, and combine them if possible so only one command/server is needed to launch it.
- [ ] Figure out how to build and host on a proper server (not a dev one)
- [ ] Use a signed SSL certificate (low priority, and likely difficult) - currently, the SSL certificate needs to be added to all browsers connecting to the server
